import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";
// import dynamic from "next/dynamic";

// const Navbar = dynamic(() => import("@/components/Navbar"), {
//   ssr: false,
// });

// const Footer = dynamic(() => import("@/components/Footer"), {
//   ssr: false,
// });
import ClientLayout from "@/components/ClientLayout";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

config.autoAddCss = false;


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pixel Craft",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Navbar /> */}
        <ClientLayout>{children}</ClientLayout>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
